### ISSUE TITLE
How did the rackets.io show itself?

### ISSUE THREAD

**Issue by alexmakeev** [martypdx/rackets.io#1]
Hi, @martypdx 
I also have a desire of merging realtime data synchranization into ractive, but not sure how it could effect stability and usability of the app.

Have you any real-world applications of the integration? Can you already say if it is a good idea of integrating such things together or no?

**Comment by martypdx** [comment]
Hey @alexmakeev, Ractive works great with realtime data. I built [cardsmith](http://cardsmith.co) - ( the app is at [gocardsmith](https://gocardsmith.co#account/register) ) using firebase instead of rolling my own websocket infrastructure, but same idea.

**Comment by alexmakeev** [comment]
Glad to hear that! Thanks for reply.
